// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcMeta.proto

package com.example.rpc.policy;

public final class NRpcProto {
  private NRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code nrpc.RPC_SERVICE_RESULT}
   */
  public enum RPC_SERVICE_RESULT
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RPC_SERVICE_OK = 0;</code>
     */
    RPC_SERVICE_OK(0, 0),
    /**
     * <code>RPC_SERVICE_FAILED = 1;</code>
     */
    RPC_SERVICE_FAILED(1, 1),
    ;

    /**
     * <code>RPC_SERVICE_OK = 0;</code>
     */
    public static final int RPC_SERVICE_OK_VALUE = 0;
    /**
     * <code>RPC_SERVICE_FAILED = 1;</code>
     */
    public static final int RPC_SERVICE_FAILED_VALUE = 1;


    public final int getNumber() { return value; }

    public static RPC_SERVICE_RESULT valueOf(int value) {
      switch (value) {
        case 0: return RPC_SERVICE_OK;
        case 1: return RPC_SERVICE_FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RPC_SERVICE_RESULT>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RPC_SERVICE_RESULT>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RPC_SERVICE_RESULT>() {
            public RPC_SERVICE_RESULT findValueByNumber(int number) {
              return RPC_SERVICE_RESULT.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.rpc.policy.NRpcProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RPC_SERVICE_RESULT[] VALUES = values();

    public static RPC_SERVICE_RESULT valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RPC_SERVICE_RESULT(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:nrpc.RPC_SERVICE_RESULT)
  }

  public interface RpcMetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .nrpc.RpcRequestMeta request = 1;
    /**
     * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
     */
    com.example.rpc.policy.NRpcProto.RpcRequestMeta getRequest();
    /**
     * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
     */
    com.example.rpc.policy.NRpcProto.RpcRequestMetaOrBuilder getRequestOrBuilder();

    // optional .nrpc.RpcResponseMeta response = 2;
    /**
     * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
     *
     * <pre>
     *optional int32 compress_type = 3;
     *optional int64 correlation_id = 4;
     *optional int32 attachment_size = 5;
     *optional ChunkInfo chunk_info = 6;
     *optional bytes authentication_data = 7;
     * </pre>
     */
    boolean hasResponse();
    /**
     * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
     *
     * <pre>
     *optional int32 compress_type = 3;
     *optional int64 correlation_id = 4;
     *optional int32 attachment_size = 5;
     *optional ChunkInfo chunk_info = 6;
     *optional bytes authentication_data = 7;
     * </pre>
     */
    com.example.rpc.policy.NRpcProto.RpcResponseMeta getResponse();
    /**
     * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
     *
     * <pre>
     *optional int32 compress_type = 3;
     *optional int64 correlation_id = 4;
     *optional int32 attachment_size = 5;
     *optional ChunkInfo chunk_info = 6;
     *optional bytes authentication_data = 7;
     * </pre>
     */
    com.example.rpc.policy.NRpcProto.RpcResponseMetaOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code nrpc.RpcMeta}
   */
  public static final class RpcMeta extends
      com.google.protobuf.GeneratedMessage
      implements RpcMetaOrBuilder {
    // Use RpcMeta.newBuilder() to construct.
    private RpcMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcMeta(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcMeta defaultInstance;
    public static RpcMeta getDefaultInstance() {
      return defaultInstance;
    }

    public RpcMeta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.example.rpc.policy.NRpcProto.RpcRequestMeta.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.example.rpc.policy.NRpcProto.RpcResponseMeta.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.rpc.policy.NRpcProto.RpcMeta.class, com.example.rpc.policy.NRpcProto.RpcMeta.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcMeta> PARSER =
        new com.google.protobuf.AbstractParser<RpcMeta>() {
      public RpcMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcMeta(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcMeta> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .nrpc.RpcRequestMeta request = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.example.rpc.policy.NRpcProto.RpcRequestMeta request_;
    /**
     * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
     */
    public com.example.rpc.policy.NRpcProto.RpcRequestMeta getRequest() {
      return request_;
    }
    /**
     * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
     */
    public com.example.rpc.policy.NRpcProto.RpcRequestMetaOrBuilder getRequestOrBuilder() {
      return request_;
    }

    // optional .nrpc.RpcResponseMeta response = 2;
    public static final int RESPONSE_FIELD_NUMBER = 2;
    private com.example.rpc.policy.NRpcProto.RpcResponseMeta response_;
    /**
     * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
     *
     * <pre>
     *optional int32 compress_type = 3;
     *optional int64 correlation_id = 4;
     *optional int32 attachment_size = 5;
     *optional ChunkInfo chunk_info = 6;
     *optional bytes authentication_data = 7;
     * </pre>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
     *
     * <pre>
     *optional int32 compress_type = 3;
     *optional int64 correlation_id = 4;
     *optional int32 attachment_size = 5;
     *optional ChunkInfo chunk_info = 6;
     *optional bytes authentication_data = 7;
     * </pre>
     */
    public com.example.rpc.policy.NRpcProto.RpcResponseMeta getResponse() {
      return response_;
    }
    /**
     * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
     *
     * <pre>
     *optional int32 compress_type = 3;
     *optional int64 correlation_id = 4;
     *optional int32 attachment_size = 5;
     *optional ChunkInfo chunk_info = 6;
     *optional bytes authentication_data = 7;
     * </pre>
     */
    public com.example.rpc.policy.NRpcProto.RpcResponseMetaOrBuilder getResponseOrBuilder() {
      return response_;
    }

    private void initFields() {
      request_ = com.example.rpc.policy.NRpcProto.RpcRequestMeta.getDefaultInstance();
      response_ = com.example.rpc.policy.NRpcProto.RpcResponseMeta.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.rpc.policy.NRpcProto.RpcMeta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nrpc.RpcMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.rpc.policy.NRpcProto.RpcMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.rpc.policy.NRpcProto.RpcMeta.class, com.example.rpc.policy.NRpcProto.RpcMeta.Builder.class);
      }

      // Construct using com.example.rpc.policy.NRpcProto.RpcMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = com.example.rpc.policy.NRpcProto.RpcRequestMeta.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (responseBuilder_ == null) {
          response_ = com.example.rpc.policy.NRpcProto.RpcResponseMeta.getDefaultInstance();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcMeta_descriptor;
      }

      public com.example.rpc.policy.NRpcProto.RpcMeta getDefaultInstanceForType() {
        return com.example.rpc.policy.NRpcProto.RpcMeta.getDefaultInstance();
      }

      public com.example.rpc.policy.NRpcProto.RpcMeta build() {
        com.example.rpc.policy.NRpcProto.RpcMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.rpc.policy.NRpcProto.RpcMeta buildPartial() {
        com.example.rpc.policy.NRpcProto.RpcMeta result = new com.example.rpc.policy.NRpcProto.RpcMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.rpc.policy.NRpcProto.RpcMeta) {
          return mergeFrom((com.example.rpc.policy.NRpcProto.RpcMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.rpc.policy.NRpcProto.RpcMeta other) {
        if (other == com.example.rpc.policy.NRpcProto.RpcMeta.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.rpc.policy.NRpcProto.RpcMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.rpc.policy.NRpcProto.RpcMeta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .nrpc.RpcRequestMeta request = 1;
      private com.example.rpc.policy.NRpcProto.RpcRequestMeta request_ = com.example.rpc.policy.NRpcProto.RpcRequestMeta.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.example.rpc.policy.NRpcProto.RpcRequestMeta, com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder, com.example.rpc.policy.NRpcProto.RpcRequestMetaOrBuilder> requestBuilder_;
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public com.example.rpc.policy.NRpcProto.RpcRequestMeta getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public Builder setRequest(com.example.rpc.policy.NRpcProto.RpcRequestMeta value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public Builder setRequest(
          com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public Builder mergeRequest(com.example.rpc.policy.NRpcProto.RpcRequestMeta value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != com.example.rpc.policy.NRpcProto.RpcRequestMeta.getDefaultInstance()) {
            request_ =
              com.example.rpc.policy.NRpcProto.RpcRequestMeta.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = com.example.rpc.policy.NRpcProto.RpcRequestMeta.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      public com.example.rpc.policy.NRpcProto.RpcRequestMetaOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .nrpc.RpcRequestMeta request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.rpc.policy.NRpcProto.RpcRequestMeta, com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder, com.example.rpc.policy.NRpcProto.RpcRequestMetaOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.rpc.policy.NRpcProto.RpcRequestMeta, com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder, com.example.rpc.policy.NRpcProto.RpcRequestMetaOrBuilder>(
                  request_,
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      // optional .nrpc.RpcResponseMeta response = 2;
      private com.example.rpc.policy.NRpcProto.RpcResponseMeta response_ = com.example.rpc.policy.NRpcProto.RpcResponseMeta.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.example.rpc.policy.NRpcProto.RpcResponseMeta, com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder, com.example.rpc.policy.NRpcProto.RpcResponseMetaOrBuilder> responseBuilder_;
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public com.example.rpc.policy.NRpcProto.RpcResponseMeta getResponse() {
        if (responseBuilder_ == null) {
          return response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public Builder setResponse(com.example.rpc.policy.NRpcProto.RpcResponseMeta value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public Builder setResponse(
          com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public Builder mergeResponse(com.example.rpc.policy.NRpcProto.RpcResponseMeta value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              response_ != com.example.rpc.policy.NRpcProto.RpcResponseMeta.getDefaultInstance()) {
            response_ =
              com.example.rpc.policy.NRpcProto.RpcResponseMeta.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = com.example.rpc.policy.NRpcProto.RpcResponseMeta.getDefaultInstance();
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder getResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      public com.example.rpc.policy.NRpcProto.RpcResponseMetaOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_;
        }
      }
      /**
       * <code>optional .nrpc.RpcResponseMeta response = 2;</code>
       *
       * <pre>
       *optional int32 compress_type = 3;
       *optional int64 correlation_id = 4;
       *optional int32 attachment_size = 5;
       *optional ChunkInfo chunk_info = 6;
       *optional bytes authentication_data = 7;
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.rpc.policy.NRpcProto.RpcResponseMeta, com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder, com.example.rpc.policy.NRpcProto.RpcResponseMetaOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.rpc.policy.NRpcProto.RpcResponseMeta, com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder, com.example.rpc.policy.NRpcProto.RpcResponseMetaOrBuilder>(
                  response_,
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:nrpc.RpcMeta)
    }

    static {
      defaultInstance = new RpcMeta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:nrpc.RpcMeta)
  }

  public interface RpcRequestMetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string service_name = 1;
    /**
     * <code>required string service_name = 1;</code>
     */
    boolean hasServiceName();
    /**
     * <code>required string service_name = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>required string service_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    // required string method_name = 2;
    /**
     * <code>required string method_name = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string method_name = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string method_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    // optional int64 log_id = 3;
    /**
     * <code>optional int64 log_id = 3;</code>
     */
    boolean hasLogId();
    /**
     * <code>optional int64 log_id = 3;</code>
     */
    long getLogId();

    // optional int64 trace_id = 4;
    /**
     * <code>optional int64 trace_id = 4;</code>
     */
    boolean hasTraceId();
    /**
     * <code>optional int64 trace_id = 4;</code>
     */
    long getTraceId();

    // optional int64 span_id = 5;
    /**
     * <code>optional int64 span_id = 5;</code>
     */
    boolean hasSpanId();
    /**
     * <code>optional int64 span_id = 5;</code>
     */
    long getSpanId();

    // optional int64 parent_span_id = 6;
    /**
     * <code>optional int64 parent_span_id = 6;</code>
     */
    boolean hasParentSpanId();
    /**
     * <code>optional int64 parent_span_id = 6;</code>
     */
    long getParentSpanId();
  }
  /**
   * Protobuf type {@code nrpc.RpcRequestMeta}
   */
  public static final class RpcRequestMeta extends
      com.google.protobuf.GeneratedMessage
      implements RpcRequestMetaOrBuilder {
    // Use RpcRequestMeta.newBuilder() to construct.
    private RpcRequestMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcRequestMeta(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcRequestMeta defaultInstance;
    public static RpcRequestMeta getDefaultInstance() {
      return defaultInstance;
    }

    public RpcRequestMeta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcRequestMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              logId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              traceId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              spanId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              parentSpanId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcRequestMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcRequestMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.rpc.policy.NRpcProto.RpcRequestMeta.class, com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcRequestMeta> PARSER =
        new com.google.protobuf.AbstractParser<RpcRequestMeta>() {
      public RpcRequestMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcRequestMeta(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequestMeta> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string service_name = 1;
    public static final int SERVICE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    /**
     * <code>required string service_name = 1;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string service_name = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string service_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string method_name = 2;
    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    /**
     * <code>required string method_name = 2;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string method_name = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 log_id = 3;
    public static final int LOG_ID_FIELD_NUMBER = 3;
    private long logId_;
    /**
     * <code>optional int64 log_id = 3;</code>
     */
    public boolean hasLogId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 log_id = 3;</code>
     */
    public long getLogId() {
      return logId_;
    }

    // optional int64 trace_id = 4;
    public static final int TRACE_ID_FIELD_NUMBER = 4;
    private long traceId_;
    /**
     * <code>optional int64 trace_id = 4;</code>
     */
    public boolean hasTraceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 trace_id = 4;</code>
     */
    public long getTraceId() {
      return traceId_;
    }

    // optional int64 span_id = 5;
    public static final int SPAN_ID_FIELD_NUMBER = 5;
    private long spanId_;
    /**
     * <code>optional int64 span_id = 5;</code>
     */
    public boolean hasSpanId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 span_id = 5;</code>
     */
    public long getSpanId() {
      return spanId_;
    }

    // optional int64 parent_span_id = 6;
    public static final int PARENT_SPAN_ID_FIELD_NUMBER = 6;
    private long parentSpanId_;
    /**
     * <code>optional int64 parent_span_id = 6;</code>
     */
    public boolean hasParentSpanId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 parent_span_id = 6;</code>
     */
    public long getParentSpanId() {
      return parentSpanId_;
    }

    private void initFields() {
      serviceName_ = "";
      methodName_ = "";
      logId_ = 0L;
      traceId_ = 0L;
      spanId_ = 0L;
      parentSpanId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, logId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, traceId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, spanId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, parentSpanId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, logId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, traceId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, spanId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, parentSpanId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcRequestMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.rpc.policy.NRpcProto.RpcRequestMeta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nrpc.RpcRequestMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.rpc.policy.NRpcProto.RpcRequestMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcRequestMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcRequestMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.rpc.policy.NRpcProto.RpcRequestMeta.class, com.example.rpc.policy.NRpcProto.RpcRequestMeta.Builder.class);
      }

      // Construct using com.example.rpc.policy.NRpcProto.RpcRequestMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        logId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        traceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        spanId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        parentSpanId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcRequestMeta_descriptor;
      }

      public com.example.rpc.policy.NRpcProto.RpcRequestMeta getDefaultInstanceForType() {
        return com.example.rpc.policy.NRpcProto.RpcRequestMeta.getDefaultInstance();
      }

      public com.example.rpc.policy.NRpcProto.RpcRequestMeta build() {
        com.example.rpc.policy.NRpcProto.RpcRequestMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.rpc.policy.NRpcProto.RpcRequestMeta buildPartial() {
        com.example.rpc.policy.NRpcProto.RpcRequestMeta result = new com.example.rpc.policy.NRpcProto.RpcRequestMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.logId_ = logId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.traceId_ = traceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.spanId_ = spanId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.parentSpanId_ = parentSpanId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.rpc.policy.NRpcProto.RpcRequestMeta) {
          return mergeFrom((com.example.rpc.policy.NRpcProto.RpcRequestMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.rpc.policy.NRpcProto.RpcRequestMeta other) {
        if (other == com.example.rpc.policy.NRpcProto.RpcRequestMeta.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasLogId()) {
          setLogId(other.getLogId());
        }
        if (other.hasTraceId()) {
          setTraceId(other.getTraceId());
        }
        if (other.hasSpanId()) {
          setSpanId(other.getSpanId());
        }
        if (other.hasParentSpanId()) {
          setParentSpanId(other.getParentSpanId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.rpc.policy.NRpcProto.RpcRequestMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.rpc.policy.NRpcProto.RpcRequestMeta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string service_name = 1;
      private java.lang.Object serviceName_ = "";
      /**
       * <code>required string service_name = 1;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string service_name = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      // required string method_name = 2;
      private java.lang.Object methodName_ = "";
      /**
       * <code>required string method_name = 2;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      // optional int64 log_id = 3;
      private long logId_ ;
      /**
       * <code>optional int64 log_id = 3;</code>
       */
      public boolean hasLogId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 log_id = 3;</code>
       */
      public long getLogId() {
        return logId_;
      }
      /**
       * <code>optional int64 log_id = 3;</code>
       */
      public Builder setLogId(long value) {
        bitField0_ |= 0x00000004;
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 log_id = 3;</code>
       */
      public Builder clearLogId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        logId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 trace_id = 4;
      private long traceId_ ;
      /**
       * <code>optional int64 trace_id = 4;</code>
       */
      public boolean hasTraceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 trace_id = 4;</code>
       */
      public long getTraceId() {
        return traceId_;
      }
      /**
       * <code>optional int64 trace_id = 4;</code>
       */
      public Builder setTraceId(long value) {
        bitField0_ |= 0x00000008;
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 trace_id = 4;</code>
       */
      public Builder clearTraceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        traceId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 span_id = 5;
      private long spanId_ ;
      /**
       * <code>optional int64 span_id = 5;</code>
       */
      public boolean hasSpanId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 span_id = 5;</code>
       */
      public long getSpanId() {
        return spanId_;
      }
      /**
       * <code>optional int64 span_id = 5;</code>
       */
      public Builder setSpanId(long value) {
        bitField0_ |= 0x00000010;
        spanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 span_id = 5;</code>
       */
      public Builder clearSpanId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        spanId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 parent_span_id = 6;
      private long parentSpanId_ ;
      /**
       * <code>optional int64 parent_span_id = 6;</code>
       */
      public boolean hasParentSpanId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 parent_span_id = 6;</code>
       */
      public long getParentSpanId() {
        return parentSpanId_;
      }
      /**
       * <code>optional int64 parent_span_id = 6;</code>
       */
      public Builder setParentSpanId(long value) {
        bitField0_ |= 0x00000020;
        parentSpanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 parent_span_id = 6;</code>
       */
      public Builder clearParentSpanId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        parentSpanId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:nrpc.RpcRequestMeta)
    }

    static {
      defaultInstance = new RpcRequestMeta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:nrpc.RpcRequestMeta)
  }

  public interface RpcResponseMetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .nrpc.RPC_SERVICE_RESULT error_code = 1;
    /**
     * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
     */
    com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT getErrorCode();

    // optional string error_text = 2;
    /**
     * <code>optional string error_text = 2;</code>
     */
    boolean hasErrorText();
    /**
     * <code>optional string error_text = 2;</code>
     */
    java.lang.String getErrorText();
    /**
     * <code>optional string error_text = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorTextBytes();
  }
  /**
   * Protobuf type {@code nrpc.RpcResponseMeta}
   */
  public static final class RpcResponseMeta extends
      com.google.protobuf.GeneratedMessage
      implements RpcResponseMetaOrBuilder {
    // Use RpcResponseMeta.newBuilder() to construct.
    private RpcResponseMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcResponseMeta(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcResponseMeta defaultInstance;
    public static RpcResponseMeta getDefaultInstance() {
      return defaultInstance;
    }

    public RpcResponseMeta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcResponseMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT value = com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                errorCode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorText_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcResponseMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcResponseMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.rpc.policy.NRpcProto.RpcResponseMeta.class, com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcResponseMeta> PARSER =
        new com.google.protobuf.AbstractParser<RpcResponseMeta>() {
      public RpcResponseMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcResponseMeta(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResponseMeta> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .nrpc.RPC_SERVICE_RESULT error_code = 1;
    public static final int ERROR_CODE_FIELD_NUMBER = 1;
    private com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT errorCode_;
    /**
     * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
     */
    public com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT getErrorCode() {
      return errorCode_;
    }

    // optional string error_text = 2;
    public static final int ERROR_TEXT_FIELD_NUMBER = 2;
    private java.lang.Object errorText_;
    /**
     * <code>optional string error_text = 2;</code>
     */
    public boolean hasErrorText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string error_text = 2;</code>
     */
    public java.lang.String getErrorText() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorTextBytes() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errorCode_ = com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT.RPC_SERVICE_OK;
      errorText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.rpc.policy.NRpcProto.RpcResponseMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.rpc.policy.NRpcProto.RpcResponseMeta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nrpc.RpcResponseMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.rpc.policy.NRpcProto.RpcResponseMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcResponseMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcResponseMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.rpc.policy.NRpcProto.RpcResponseMeta.class, com.example.rpc.policy.NRpcProto.RpcResponseMeta.Builder.class);
      }

      // Construct using com.example.rpc.policy.NRpcProto.RpcResponseMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorCode_ = com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT.RPC_SERVICE_OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.rpc.policy.NRpcProto.internal_static_nrpc_RpcResponseMeta_descriptor;
      }

      public com.example.rpc.policy.NRpcProto.RpcResponseMeta getDefaultInstanceForType() {
        return com.example.rpc.policy.NRpcProto.RpcResponseMeta.getDefaultInstance();
      }

      public com.example.rpc.policy.NRpcProto.RpcResponseMeta build() {
        com.example.rpc.policy.NRpcProto.RpcResponseMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.rpc.policy.NRpcProto.RpcResponseMeta buildPartial() {
        com.example.rpc.policy.NRpcProto.RpcResponseMeta result = new com.example.rpc.policy.NRpcProto.RpcResponseMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorText_ = errorText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.rpc.policy.NRpcProto.RpcResponseMeta) {
          return mergeFrom((com.example.rpc.policy.NRpcProto.RpcResponseMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.rpc.policy.NRpcProto.RpcResponseMeta other) {
        if (other == com.example.rpc.policy.NRpcProto.RpcResponseMeta.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorText()) {
          bitField0_ |= 0x00000002;
          errorText_ = other.errorText_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.rpc.policy.NRpcProto.RpcResponseMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.rpc.policy.NRpcProto.RpcResponseMeta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .nrpc.RPC_SERVICE_RESULT error_code = 1;
      private com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT errorCode_ = com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT.RPC_SERVICE_OK;
      /**
       * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
       */
      public com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
       */
      public Builder setErrorCode(com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .nrpc.RPC_SERVICE_RESULT error_code = 1;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = com.example.rpc.policy.NRpcProto.RPC_SERVICE_RESULT.RPC_SERVICE_OK;
        onChanged();
        return this;
      }

      // optional string error_text = 2;
      private java.lang.Object errorText_ = "";
      /**
       * <code>optional string error_text = 2;</code>
       */
      public boolean hasErrorText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public java.lang.String getErrorText() {
        java.lang.Object ref = errorText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorTextBytes() {
        java.lang.Object ref = errorText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public Builder setErrorText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public Builder clearErrorText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorText_ = getDefaultInstance().getErrorText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 2;</code>
       */
      public Builder setErrorTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorText_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:nrpc.RpcResponseMeta)
    }

    static {
      defaultInstance = new RpcResponseMeta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:nrpc.RpcResponseMeta)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nrpc_RpcMeta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nrpc_RpcMeta_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nrpc_RpcRequestMeta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nrpc_RpcRequestMeta_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nrpc_RpcResponseMeta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nrpc_RpcResponseMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRpcMeta.proto\022\004nrpc\"Y\n\007RpcMeta\022%\n\007requ" +
      "est\030\001 \001(\0132\024.nrpc.RpcRequestMeta\022\'\n\010respo" +
      "nse\030\002 \001(\0132\025.nrpc.RpcResponseMeta\"\206\001\n\016Rpc" +
      "RequestMeta\022\024\n\014service_name\030\001 \002(\t\022\023\n\013met" +
      "hod_name\030\002 \002(\t\022\016\n\006log_id\030\003 \001(\003\022\020\n\010trace_" +
      "id\030\004 \001(\003\022\017\n\007span_id\030\005 \001(\003\022\026\n\016parent_span" +
      "_id\030\006 \001(\003\"S\n\017RpcResponseMeta\022,\n\nerror_co" +
      "de\030\001 \001(\0162\030.nrpc.RPC_SERVICE_RESULT\022\022\n\ner" +
      "ror_text\030\002 \001(\t*@\n\022RPC_SERVICE_RESULT\022\022\n\016" +
      "RPC_SERVICE_OK\020\000\022\026\n\022RPC_SERVICE_FAILED\020\001",
      "B#\n\026com.example.rpc.policyB\tNRpcProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nrpc_RpcMeta_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nrpc_RpcMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nrpc_RpcMeta_descriptor,
              new java.lang.String[] { "Request", "Response", });
          internal_static_nrpc_RpcRequestMeta_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_nrpc_RpcRequestMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nrpc_RpcRequestMeta_descriptor,
              new java.lang.String[] { "ServiceName", "MethodName", "LogId", "TraceId", "SpanId", "ParentSpanId", });
          internal_static_nrpc_RpcResponseMeta_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_nrpc_RpcResponseMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nrpc_RpcResponseMeta_descriptor,
              new java.lang.String[] { "ErrorCode", "ErrorText", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
